### ISSUE TITLE
Hardcoded Default deploy user

### ISSUE THREAD

**Issue by chandresh** [TalkingQuickly/capistrano-cookbook#10]
Hi...

The default AS_USER set in unicorn_init.sh.erb is hardcoded as deploy. Here is relevant code:

``` ruby
  TIMEOUT=${TIMEOUT-60}
  APP_ROOT=<%= current_path %>
  PID_DIR=$APP_ROOT/tmp/pids
  PID=$PID_DIR/unicorn.pid
  CMD="cd $APP_ROOT;  bundle exec unicorn -D -c <%= "#{shared_path}/config/unicorn.rb" %> -E <%= fetch(:rails_env) %>"
  AS_USER=deploy
  set -u
```

Can we instead use a variable here? I think I can send a pull request if required.

**Comment by TalkingQuickly** [comment]
Agreed, this is now resolved in the updated puma configuration which replaces the unicorn config
