### ISSUE TITLE
Config files per stage selected uncorrectly

### ISSUE THREAD

**Issue by rolandboon** [TalkingQuickly/capistrano-cookbook#11]
In the readme the following sequence for selecting ERB files for `deploy:setup_config` is mentioned:
- config/deploy/STAGE/FILENAME.erb
- config/deploy/shared/FILENAME.erb
- templates/FILENAME.erb

However, in [helpers/template.rb](https://github.com/TalkingQuickly/capistrano-cookbook/blob/master/lib/capistrano/cookbook/helpers/template.rb#L27) the first directory where is looked for an ERB is `"config/deploy/#{fetch(:full_app_name)}/#{name}.erb")`.

**Comment by marshallmick007** [comment]
Any word on accepting this pull request? I spent an hour trying to figure out why my custom config files were not being picked up before digging through the source to find this same issue.

**Comment by TalkingQuickly** [comment]
@marshallmick007 thanks for reminding me and @rolandboon thanks for the reminder. I've now merged it so if you use the Gem from Github the fix is there. I'll get a new release of the gem out and the sample code updated shortly.

**Comment by TalkingQuickly** [comment]
All fixed in the latest release of the gem
